# Aggregate Results

In [31]:
import pandas as pd

In [32]:
infile_path = '~/Development/Smart-Mater-Installation-Scheduling-Project/Smart-Mater-Installation-Scheduling-Project/output/Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz/results_grasp/parameter_tuning/results_grasp_instance_10_6.csv'

In [33]:
df = pd.read_csv(infile_path)

In [34]:
df.head()

,Alpha,Beta,Chi,Delta,Epsilon,MaxIter,Seed,ObjBest,Runtime,NumIterations,...,RuntimeBest,NumIterationsFirstMethod,CumulativeRuntimeFirstMethod,NumIterationsSecondMethod,CumulativeRuntimeSecondMethod,NumIterationsThirdMethod,CumulativeRuntimeThirdMethod,NumIterationsFourthMethod,CumulativeRuntimeFourthMethod,RuntimeTieModel
0,2.0,0.0,0.8,0.7,0.05,50,123,-37562.33,1219.20,50,...,445.37,0,0.0,288,964.34,94,242.34,57,10.98,0.0
1,2.0,0.0,0.8,0.7,0.05,50,321,-37573.73,1122.22,50,...,107.31,0,0.0,273,920.97,88,187.92,53,11.73,0.0
2,2.0,0.0,0.8,0.7,0.10,50,123,-37562.33,1214.35,50,...,442.68,0,0.0,288,959.59,94,242.26,57,10.99,0.0
3,2.0,0.0,0.8,0.7,0.10,50,321,-37573.73,1124.31,50,...,107.44,0,0.0,273,923.05,88,187.99,53,11.71,0.0
4,2.0,0.0,0.8,0.7,0.15,50,123,-37691.61,1173.18,50,...,62.54,0,0.0,291,965.85,85,151.64,57,54.19,0.0

In [35]:
df['Instance'] = df.index.map(lambda idx: 'instance_10_6_2022_2' if idx < 384 else 'instance_10_6_2024_5')

In [36]:
df.columns

Index(['Alpha', 'Beta', 'Chi', 'Delta', 'Epsilon', 'MaxIter', 'Seed',
       'ObjBest', 'Runtime', 'NumIterations',
       'NumIterations (to find the best solution)', 'RuntimeBest',
       'NumIterationsFirstMethod', 'CumulativeRuntimeFirstMethod',
       'NumIterationsSecondMethod', 'CumulativeRuntimeSecondMethod',
       'NumIterationsThirdMethod', 'CumulativeRuntimeThirdMethod',
       'NumIterationsFourthMethod', 'CumulativeRuntimeFourthMethod',
       'RuntimeTieModel', 'Instance'],
      dtype='object')

In [37]:
cols = ['Instance'] + [col for col in df.columns if col != 'Instance']

In [38]:
df = df[cols]

In [39]:
df.head()

,Instance,Alpha,Beta,Chi,Delta,Epsilon,MaxIter,Seed,ObjBest,Runtime,...,RuntimeBest,NumIterationsFirstMethod,CumulativeRuntimeFirstMethod,NumIterationsSecondMethod,CumulativeRuntimeSecondMethod,NumIterationsThirdMethod,CumulativeRuntimeThirdMethod,NumIterationsFourthMethod,CumulativeRuntimeFourthMethod,RuntimeTieModel
0,instance_10_6_2022_2,2.0,0.0,0.8,0.7,0.05,50,123,-37562.33,1219.20,...,445.37,0,0.0,288,964.34,94,242.34,57,10.98,0.0
1,instance_10_6_2022_2,2.0,0.0,0.8,0.7,0.05,50,321,-37573.73,1122.22,...,107.31,0,0.0,273,920.97,88,187.92,53,11.73,0.0
2,instance_10_6_2022_2,2.0,0.0,0.8,0.7,0.10,50,123,-37562.33,1214.35,...,442.68,0,0.0,288,959.59,94,242.26,57,10.99,0.0
3,instance_10_6_2022_2,2.0,0.0,0.8,0.7,0.10,50,321,-37573.73,1124.31,...,107.44,0,0.0,273,923.05,88,187.99,53,11.71,0.0
4,instance_10_6_2022_2,2.0,0.0,0.8,0.7,0.15,50,123,-37691.61,1173.18,...,62.54,0,0.0,291,965.85,85,151.64,57,54.19,0.0

In [40]:
df.tail(5)

,Instance,Alpha,Beta,Chi,Delta,Epsilon,MaxIter,Seed,ObjBest,Runtime,...,RuntimeBest,NumIterationsFirstMethod,CumulativeRuntimeFirstMethod,NumIterationsSecondMethod,CumulativeRuntimeSecondMethod,NumIterationsThirdMethod,CumulativeRuntimeThirdMethod,NumIterationsFourthMethod,CumulativeRuntimeFourthMethod,RuntimeTieModel
763,instance_10_6_2024_5,6.0,0.0,0.95,0.85,0.10,50,321,-21708.96,214.26,...,55.15,0,0.0,236,19.58,186,160.34,128,32.78,0.0
764,instance_10_6_2024_5,6.0,0.0,0.95,0.85,0.15,50,123,-21047.56,511.65,...,166.55,0,0.0,301,25.04,251,212.28,171,272.79,0.0
765,instance_10_6_2024_5,6.0,0.0,0.95,0.85,0.15,50,321,-21286.22,490.58,...,202.50,0,0.0,285,23.58,235,170.11,168,295.33,0.0
766,instance_10_6_2024_5,6.0,0.0,0.95,0.85,0.20,50,123,-21047.56,512.96,...,167.42,0,0.0,301,24.77,251,212.43,171,274.15,0.0
767,instance_10_6_2024_5,6.0,0.0,0.95,0.85,0.20,50,321,-21286.22,490.32,...,202.69,0,0.0,285,23.51,235,170.23,168,294.97,0.0

In [41]:
df.describe()

,Alpha,Beta,Chi,Delta,Epsilon,MaxIter,Seed,ObjBest,Runtime,NumIterations,...,RuntimeBest,NumIterationsFirstMethod,CumulativeRuntimeFirstMethod,NumIterationsSecondMethod,CumulativeRuntimeSecondMethod,NumIterationsThirdMethod,CumulativeRuntimeThirdMethod,NumIterationsFourthMethod,CumulativeRuntimeFourthMethod,RuntimeTieModel
count,768.000000,768.0,768.000000,768.000000,768.000000,768.0,768.000000,768.000000,768.000000,768.0,...,768.000000,768.0,768.0,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.0
mean,4.000000,0.0,0.875000,0.775000,0.125000,50.0,222.000000,-29474.926667,595.204609,50.0,...,274.420911,0.0,0.0,285.272135,321.718685,133.738281,202.629297,83.647135,69.302201,0.0
std,1.634057,0.0,0.055938,0.055938,0.055938,0.0,99.064516,8477.196988,401.608523,0.0,...,259.323136,0.0,0.0,44.693424,427.079155,37.116652,97.445077,22.255520,62.221337,0.0
min,2.000000,0.0,0.800000,0.700000,0.050000,50.0,123.000000,-41369.600000,95.250000,50.0,...,3.220000,0.0,0.0,164.000000,13.280000,72.000000,32.590000,53.000000,9.600000,0.0
25%,2.000000,0.0,0.837500,0.737500,0.087500,50.0,123.000000,-37691.610000,321.320000,50.0,...,91.830000,0.0,0.0,257.750000,65.122500,104.000000,126.112500,68.000000,15.540000,0.0
50%,4.000000,0.0,0.875000,0.775000,0.125000,50.0,222.000000,-30705.000000,440.000000,50.0,...,197.015000,0.0,0.0,293.000000,106.070000,130.000000,200.625000,77.000000,42.520000,0.0
75%,6.000000,0.0,0.912500,0.812500,0.162500,50.0,321.000000,-20888.880000,707.417500,50.0,...,364.747500,0.0,0.0,316.000000,314.925000,153.250000,275.657500,94.000000,114.342500,0.0
max,6.000000,0.0,0.950000,0.850000,0.200000,50.0,321.000000,-20281.470000,1544.350000,50.0,...,1371.090000,0.0,0.0,392.000000,1269.500000,253.000000,486.220000,171.000000,295.330000,0.0

In [42]:
outfile_path = '~/Development/Smart-Mater-Installation-Scheduling-Project/Smart-Mater-Installation-Scheduling-Project/output/Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz/results_grasp/parameter_tuning/results_grasp_instance_10_6.csv'

In [43]:
df.to_csv(outfile_path, index=False)

# Filter **df** and create **df_ins_1** and **df_ins_2**.

In [44]:
df_ins_1 = df[df['Instance'] == 'instance_10_6_2022_2']

In [45]:
df_ins_1

,Instance,Alpha,Beta,Chi,Delta,Epsilon,MaxIter,Seed,ObjBest,Runtime,...,RuntimeBest,NumIterationsFirstMethod,CumulativeRuntimeFirstMethod,NumIterationsSecondMethod,CumulativeRuntimeSecondMethod,NumIterationsThirdMethod,CumulativeRuntimeThirdMethod,NumIterationsFourthMethod,CumulativeRuntimeFourthMethod,RuntimeTieModel
0,instance_10_6_2022_2,2.0,0.0,0.80,0.70,0.05,50,123,-37562.33,1219.20,...,445.37,0,0.0,288,964.34,94,242.34,57,10.98,0.0
1,instance_10_6_2022_2,2.0,0.0,0.80,0.70,0.05,50,321,-37573.73,1122.22,...,107.31,0,0.0,273,920.97,88,187.92,53,11.73,0.0
2,instance_10_6_2022_2,2.0,0.0,0.80,0.70,0.10,50,123,-37562.33,1214.35,...,442.68,0,0.0,288,959.59,94,242.26,57,10.99,0.0
3,instance_10_6_2022_2,2.0,0.0,0.80,0.70,0.10,50,321,-37573.73,1124.31,...,107.44,0,0.0,273,923.05,88,187.99,53,11.71,0.0
4,instance_10_6_2022_2,2.0,0.0,0.80,0.70,0.15,50,123,-37691.61,1173.18,...,62.54,0,0.0,291,965.85,85,151.64,57,54.19,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,instance_10_6_2022_2,6.0,0.0,0.95,0.85,0.10,50,321,-40660.86,192.66,...,43.08,0,0.0,215,17.64,165,145.84,112,27.58,0.0
380,instance_10_6_2022_2,6.0,0.0,0.95,0.85,0.15,50,123,-38283.88,399.05,...,226.59,0,0.0,269,22.26,219,126.77,156,248.39,0.0
381,instance_10_6_2022_2,6.0,0.0,0.95,0.85,0.15,50,321,-37816.37,414.42,...,250.91,0,0.0,278,22.95,228,130.88,162,259.04,0.0
382,instance_10_6_2022_2,6.0,0.0,0.95,0.85,0.20,50,123,-38283.88,397.45,...,225.81,0,0.0,269,22.27,219,126.41,156,247.24,0.0
383,instance_10_6_2022_2,6.0,0.0,0.95,0.85,0.20,50,321,-37816.37,413.91,...,250.67,0,0.0,278,22.74,228,130.71,162,258.91,0.0

In [46]:
df_ins_1.describe()

,Alpha,Beta,Chi,Delta,Epsilon,MaxIter,Seed,ObjBest,Runtime,NumIterations,...,RuntimeBest,NumIterationsFirstMethod,CumulativeRuntimeFirstMethod,NumIterationsSecondMethod,CumulativeRuntimeSecondMethod,NumIterationsThirdMethod,CumulativeRuntimeThirdMethod,NumIterationsFourthMethod,CumulativeRuntimeFourthMethod,RuntimeTieModel
count,384.000000,384.0,384.000000,384.000000,384.000000,384.0,384.000000,384.000000,384.000000,384.0,...,384.000000,384.0,384.0,384.000000,384.000000,384.000000,384.000000,384.000000,384.000000,384.0
mean,4.000000,0.0,0.875000,0.775000,0.125000,50.0,222.000000,-37919.745182,588.691432,50.0,...,265.802604,0.0,0.0,283.507812,313.218255,133.794271,206.589375,81.830729,67.326745,0.0
std,1.635124,0.0,0.055975,0.055975,0.055975,0.0,99.129159,615.154285,389.912020,0.0,...,239.624628,0.0,0.0,38.078385,413.138580,35.472666,103.712385,20.351224,58.504632,0.0
min,2.000000,0.0,0.800000,0.700000,0.050000,50.0,123.000000,-41369.600000,115.990000,50.0,...,9.820000,0.0,0.0,184.000000,14.990000,73.000000,32.590000,53.000000,10.630000,0.0
25%,2.000000,0.0,0.837500,0.737500,0.087500,50.0,123.000000,-38175.350000,325.517500,50.0,...,107.407500,0.0,0.0,264.750000,70.642500,104.000000,124.465000,67.000000,15.842500,0.0
50%,4.000000,0.0,0.875000,0.775000,0.125000,50.0,222.000000,-37691.610000,437.670000,50.0,...,193.820000,0.0,0.0,294.000000,105.340000,133.000000,208.790000,77.000000,40.145000,0.0
75%,6.000000,0.0,0.912500,0.812500,0.162500,50.0,321.000000,-37562.330000,707.417500,50.0,...,361.727500,0.0,0.0,309.500000,311.875000,153.000000,280.222500,91.000000,116.427500,0.0
max,6.000000,0.0,0.950000,0.850000,0.200000,50.0,321.000000,-37562.330000,1500.320000,50.0,...,1128.700000,0.0,0.0,340.000000,1139.640000,229.000000,486.220000,162.000000,259.040000,0.0

In [47]:
df_ins_2 = df[df['Instance'] == 'instance_10_6_2024_5']

In [48]:
df_ins_2

,Instance,Alpha,Beta,Chi,Delta,Epsilon,MaxIter,Seed,ObjBest,Runtime,...,RuntimeBest,NumIterationsFirstMethod,CumulativeRuntimeFirstMethod,NumIterationsSecondMethod,CumulativeRuntimeSecondMethod,NumIterationsThirdMethod,CumulativeRuntimeThirdMethod,NumIterationsFourthMethod,CumulativeRuntimeFourthMethod,RuntimeTieModel
384,instance_10_6_2024_5,2.0,0.0,0.80,0.70,0.05,50,123,-20389.52,1176.03,...,394.38,0,0.0,277,980.87,86,182.68,53,10.97,0.0
385,instance_10_6_2024_5,2.0,0.0,0.80,0.70,0.05,50,321,-20422.41,1024.62,...,824.08,0,0.0,235,829.08,83,184.40,55,9.60,0.0
386,instance_10_6_2024_5,2.0,0.0,0.80,0.70,0.10,50,123,-20389.52,1177.04,...,394.95,0,0.0,277,981.79,86,182.75,53,10.99,0.0
387,instance_10_6_2024_5,2.0,0.0,0.80,0.70,0.10,50,321,-20422.41,1026.18,...,825.30,0,0.0,235,830.57,83,184.46,55,9.64,0.0
388,instance_10_6_2024_5,2.0,0.0,0.80,0.70,0.15,50,123,-20281.47,1414.66,...,878.32,0,0.0,304,1104.03,104,229.49,70,79.63,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763,instance_10_6_2024_5,6.0,0.0,0.95,0.85,0.10,50,321,-21708.96,214.26,...,55.15,0,0.0,236,19.58,186,160.34,128,32.78,0.0
764,instance_10_6_2024_5,6.0,0.0,0.95,0.85,0.15,50,123,-21047.56,511.65,...,166.55,0,0.0,301,25.04,251,212.28,171,272.79,0.0
765,instance_10_6_2024_5,6.0,0.0,0.95,0.85,0.15,50,321,-21286.22,490.58,...,202.50,0,0.0,285,23.58,235,170.11,168,295.33,0.0
766,instance_10_6_2024_5,6.0,0.0,0.95,0.85,0.20,50,123,-21047.56,512.96,...,167.42,0,0.0,301,24.77,251,212.43,171,274.15,0.0
767,instance_10_6_2024_5,6.0,0.0,0.95,0.85,0.20,50,321,-21286.22,490.32,...,202.69,0,0.0,285,23.51,235,170.23,168,294.97,0.0

In [49]:
df_ins_2.describe()

,Alpha,Beta,Chi,Delta,Epsilon,MaxIter,Seed,ObjBest,Runtime,NumIterations,...,RuntimeBest,NumIterationsFirstMethod,CumulativeRuntimeFirstMethod,NumIterationsSecondMethod,CumulativeRuntimeSecondMethod,NumIterationsThirdMethod,CumulativeRuntimeThirdMethod,NumIterationsFourthMethod,CumulativeRuntimeFourthMethod,RuntimeTieModel
count,384.000000,384.0,384.000000,384.000000,384.000000,384.0,384.000000,384.000000,384.000000,384.0,...,384.000000,384.0,384.0,384.000000,384.000000,384.000000,384.000000,384.000000,384.000000,384.0
mean,4.000000,0.0,0.875000,0.775000,0.125000,50.0,222.000000,-21030.108151,601.717786,50.0,...,283.039219,0.0,0.0,287.036458,330.219115,133.682292,198.669219,85.463542,71.277656,0.0
std,1.635124,0.0,0.055975,0.055975,0.055975,0.0,99.129159,729.817013,413.380557,0.0,...,277.675458,0.0,0.0,50.438223,440.954717,38.737223,90.709280,23.898146,65.745575,0.0
min,2.000000,0.0,0.800000,0.700000,0.050000,50.0,123.000000,-23847.670000,95.250000,50.0,...,3.220000,0.0,0.0,164.000000,13.280000,72.000000,35.020000,53.000000,9.600000,0.0
25%,2.000000,0.0,0.837500,0.737500,0.087500,50.0,123.000000,-21232.690000,312.070000,50.0,...,86.337500,0.0,0.0,252.500000,65.122500,103.750000,130.872500,68.000000,15.360000,0.0
50%,4.000000,0.0,0.875000,0.775000,0.125000,50.0,222.000000,-20888.880000,441.145000,50.0,...,206.260000,0.0,0.0,286.000000,106.905000,126.500000,192.860000,79.000000,42.520000,0.0
75%,6.000000,0.0,0.912500,0.812500,0.162500,50.0,321.000000,-20430.590000,709.312500,50.0,...,370.697500,0.0,0.0,326.000000,314.925000,154.000000,261.457500,97.000000,113.092500,0.0
max,6.000000,0.0,0.950000,0.850000,0.200000,50.0,321.000000,-20281.470000,1544.350000,50.0,...,1371.090000,0.0,0.0,392.000000,1269.500000,253.000000,450.800000,171.000000,295.330000,0.0

# Use **groupby** to create **mean_df_ins_1** write it to a CSV file.

In [50]:
group_cols = ['Instance', 'Alpha', 'Beta', 'Chi', 'Delta', 'Epsilon']

In [51]:
exclude_cols = ['MaxIter', 'Seed', 'TimeLimit']

In [52]:
mean_cols = ['ObjBest', 'Runtime', 'NumIterations', 'NumIterations (to find the best solution)', 'RuntimeBest', 'NumIterationsFirstMethod', 'CumulativeRuntimeFirstMethod', 'NumIterationsSecondMethod', 'CumulativeRuntimeSecondMethod', 'NumIterationsThirdMethod', 'CumulativeRuntimeThirdMethod', 'NumIterationsFourthMethod', 'CumulativeRuntimeFourthMethod']

In [53]:
mean_df_ins_1 = df_ins_1.groupby(group_cols)[mean_cols].mean().reset_index()

In [54]:
print(mean_df_ins_1)

                 Instance  Alpha  Beta   Chi  Delta  Epsilon    ObjBest  \
0    instance_10_6_2022_2    2.0   0.0  0.80   0.70     0.05 -37568.030
1    instance_10_6_2022_2    2.0   0.0  0.80   0.70     0.10 -37568.030
2    instance_10_6_2022_2    2.0   0.0  0.80   0.70     0.15 -37626.970
3    instance_10_6_2022_2    2.0   0.0  0.80   0.70     0.20 -37626.970
4    instance_10_6_2022_2    2.0   0.0  0.80   0.75     0.05 -37562.330
..                    ...    ...   ...   ...    ...      ...        ...
187  instance_10_6_2022_2    6.0   0.0  0.95   0.80     0.20 -38256.670
188  instance_10_6_2022_2    6.0   0.0  0.95   0.85     0.05 -40361.000
189  instance_10_6_2022_2    6.0   0.0  0.95   0.85     0.10 -40361.000
190  instance_10_6_2022_2    6.0   0.0  0.95   0.85     0.15 -38050.125
191  instance_10_6_2022_2    6.0   0.0  0.95   0.85     0.20 -38050.125

      Runtime  NumIterations  NumIterations (to find the best solution)  \
0    1170.710           50.0                                        9.5
1    1169.330           50.0                                        9.5
2    1216.930           50.0                                       16.5
3    1225.310           50.0                                       16.5
4    1238.150           50.0                                       26.0
..        ...            ...                                        ...
187   504.475           50.0                                       29.0
188   186.045           50.0                                       17.5
189   186.210           50.0                                       17.5
190   406.735           50.0                                       26.5
191   405.680           50.0                                       26.5

     RuntimeBest  NumIterationsFirstMethod  CumulativeRuntimeFirstMethod  \
0        276.340                       0.0                           0.0
1        275.060                       0.0                           0.0
2        430.900                       0.0                           0.0
3        434.205                       0.0                           0.0
4        641.000                       0.0                           0.0
..           ...                       ...                           ...
187      312.960                       0.0                           0.0
188       78.465                       0.0                           0.0
189       78.485                       0.0                           0.0
190      238.750                       0.0                           0.0
191      238.240                       0.0                           0.0

     NumIterationsSecondMethod  CumulativeRuntimeSecondMethod  \
0                        280.5                        942.655
1                        280.5                        941.320
2                        288.0                        973.135
3                        288.0                        980.880
4                        293.5                        993.060
..                         ...                            ...
187                      257.5                         21.380
188                      207.0                         16.890
189                      207.0                         16.980
190                      273.5                         22.605
191                      273.5                         22.505

     NumIterationsThirdMethod  CumulativeRuntimeThirdMethod  \
0                        91.0                       215.130
1                        91.0                       215.125
2                        91.5                       177.545
3                        91.5                       177.750
4                        98.5                       230.190
..                        ...                           ...
187                     206.5                       297.735
188                     157.0                       142.430
189                     157.0                       142.485
190                     223.5                       128.825
191                     223.5                       128.560

     NumIterationsFourthMethod  CumulativeRuntimeFourthMethod
0                         55.0                         11.355
1                         55.0                         11.350
2                         59.5                         64.715
3                         59.5                         65.155
4                         59.5                         13.370
..                         ...                            ...
187                      141.5                        183.760
188                      103.0                         25.130
189                      103.0                         25.180
190                      159.0                        253.715
191                      159.0                        253.075

[192 rows x 19 columns]

In [55]:
outfile_path = '~/Development/Smart-Mater-Installation-Scheduling-Project/Smart-Mater-Installation-Scheduling-Project/output/Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz/results_grasp/parameter_tuning/results_grasp_instance_10_6_2022_2.csv'

In [56]:
mean_df_ins_1.to_csv(outfile_path, index=False)

# Use **groupby** to create **mean_df_ins_2** and write it to a CSV file.

In [57]:
mean_df_ins_2 = df_ins_2.groupby(group_cols)[mean_cols].mean().reset_index()

In [58]:
print(mean_df_ins_2)

                 Instance  Alpha  Beta   Chi  Delta  Epsilon    ObjBest  \
0    instance_10_6_2024_5    2.0   0.0  0.80   0.70     0.05 -20405.965
1    instance_10_6_2024_5    2.0   0.0  0.80   0.70     0.10 -20405.965
2    instance_10_6_2024_5    2.0   0.0  0.80   0.70     0.15 -20335.495
3    instance_10_6_2024_5    2.0   0.0  0.80   0.70     0.20 -20335.495
4    instance_10_6_2024_5    2.0   0.0  0.80   0.75     0.05 -20410.055
..                    ...    ...   ...   ...    ...      ...        ...
187  instance_10_6_2024_5    6.0   0.0  0.95   0.80     0.20 -21189.270
188  instance_10_6_2024_5    6.0   0.0  0.95   0.85     0.05 -22380.940
189  instance_10_6_2024_5    6.0   0.0  0.95   0.85     0.10 -22380.940
190  instance_10_6_2024_5    6.0   0.0  0.95   0.85     0.15 -21166.890
191  instance_10_6_2024_5    6.0   0.0  0.95   0.85     0.20 -21166.890

      Runtime  NumIterations  NumIterations (to find the best solution)  \
0    1100.325           50.0                                       28.0
1    1101.610           50.0                                       28.0
2    1387.875           50.0                                       26.5
3    1383.275           50.0                                       26.5
4    1098.075           50.0                                       13.5
..        ...            ...                                        ...
187   603.805           50.0                                       31.5
188   241.035           50.0                                       20.5
189   241.105           50.0                                       20.5
190   501.115           50.0                                       16.5
191   501.640           50.0                                       16.5

     RuntimeBest  NumIterationsFirstMethod  CumulativeRuntimeFirstMethod  \
0        609.230                       0.0                           0.0
1        610.125                       0.0                           0.0
2        778.365                       0.0                           0.0
3        774.520                       0.0                           0.0
4        314.460                       0.0                           0.0
..           ...                       ...                           ...
187      394.325                       0.0                           0.0
188      112.755                       0.0                           0.0
189      112.810                       0.0                           0.0
190      184.525                       0.0                           0.0
191      185.055                       0.0                           0.0

     NumIterationsSecondMethod  CumulativeRuntimeSecondMethod  \
0                        256.0                        904.975
1                        256.0                        906.180
2                        300.0                       1073.785
3                        300.0                       1069.450
4                        262.0                        917.355
..                         ...                            ...
187                      301.5                         24.995
188                      246.0                         20.335
189                      246.0                         20.315
190                      293.0                         24.310
191                      293.0                         24.140

     NumIterationsThirdMethod  CumulativeRuntimeThirdMethod  \
0                        84.5                       183.540
1                        84.5                       183.605
2                       105.5                       241.590
3                       105.5                       241.555
4                        83.5                       167.115
..                        ...                           ...
187                     250.0                       333.335
188                     195.5                       185.480
189                     195.5                       185.565
190                     243.0                       191.195
191                     243.0                       191.330

     NumIterationsFourthMethod  CumulativeRuntimeFourthMethod
0                         54.0                         10.285
1                         54.0                         10.315
2                         66.0                         70.960
3                         66.0                         70.775
4                         56.0                         12.050
..                         ...                            ...
187                      162.5                        243.920
188                      134.0                         33.670
189                      134.0                         33.670
190                      169.5                        284.060
191                      169.5                        284.560

[192 rows x 19 columns]

In [59]:
outfile_path = '~/Development/Smart-Mater-Installation-Scheduling-Project/Smart-Mater-Installation-Scheduling-Project/output/Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz/results_grasp/parameter_tuning/results_grasp_instance_10_6_2024_5.csv'

In [60]:
mean_df_ins_2.to_csv(outfile_path, index=False)